# -*- coding: utf-8 -*-
# Generated by Django 1.9a1 on 2015-10-04 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printo_app', '0002_auto_20151004_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='is_email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_person_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='is_sms_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organization',
            name='time_email_verified',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='time_person_verified',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
